//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasheShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomizeSetting
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string path { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public string fulldescription { get; set; }
        public string newprice { get; set; }
    }
}
